import assert from 'node:assert/strict'
import {socialKit} from './helpers/social-live.mjs'
const k=await socialKit(['profile_follows','community_posts','social_publish_log','library_activity'])
let count=0
async function check(name,fn){await fn();count++;console.log('PASS',name)}
try {
 const a=await k.user('Author'),b=await k.user('Other'),{page,ctx}=await k.context(a),guest=await k.context()
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 let action,topic
 page.on('request',r=>{if(r.method()==='POST'&&r.headers()['next-action'])action=r.headers()['next-action']})
 await check('publish, spoiler toggle and plain-text HTML render through the browser',async()=>{
  await page.route('https://images.example.test/topic.png',route=>route.fulfill({status:404,body:'missing'}))
  await page.goto(k.base+'/community/new');await page.getByLabel('Título',{exact:true}).fill('Tópico '+k.prefix)
  await page.getByLabel('Texto',{exact:true}).fill('<b>Uma conversa sobre animes</b>')
  await page.getByLabel('Imagem HTTPS (opcional)',{exact:true}).fill('https://images.example.test/topic.png')
  await page.getByLabel('Contém spoilers',{exact:true}).check();await page.getByRole('button',{name:'Publicar tópico',exact:true}).click();await page.waitForURL(/\/community\/[a-f0-9-]+$/)
  topic=new URL(page.url()).pathname.split('/').at(-1)
  assert.equal(await page.locator('details').evaluate(el=>el.open),false)
  await page.getByText('Mostrar conteúdo com spoilers',{exact:true}).click()
  await page.getByText('<b>Uma conversa sobre animes</b>',{exact:true}).waitFor();assert.equal(await page.locator('article b').count(),0)
  await page.getByText('Imagem indisponível.',{exact:true}).waitFor()
  await guest.page.goto(page.url());await guest.page.getByRole('heading',{name:'Tópico '+k.prefix,exact:true}).waitFor()
 })
 await check('automoderation applies to edits, and immediate new publication is throttled',async()=>{
  const editResponse=await page.goto(`${k.base}/community/${topic}/edit`)
  assert.equal(editResponse.status(),200,`Edit page missing: ${topic}`)
  await page.getByLabel('Texto',{exact:true}).fill('v.i.a.d.i.n.h.o')
  await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();await page.getByRole('alert').getByText(/linguagem discriminatória/).waitFor()
  assert.equal(k.unwrap(await k.db.from('community_posts').select('body').eq('id',topic).single()).body,'<b>Uma conversa sobre animes</b>')
  await page.getByLabel('Texto',{exact:true}).fill('Que merda de final, vamos discutir.');await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();await page.waitForURL(`${k.base}/community/${topic}`)
  await page.goto(k.base+'/community/new');await page.getByLabel('Título',{exact:true}).fill('Outro tópico');await page.getByLabel('Texto',{exact:true}).fill('Outro texto respeitoso')
  await page.getByRole('button',{name:'Publicar tópico',exact:true}).click();await page.getByRole('alert').getByText(/Aguarde \d+ segundos/).waitFor()
 })
 await check('ownership, anonymous writes and profile privacy are enforced',async()=>{
  const payload={p_actor:b.id,p_id:topic,p_title:'forged',p_body:'forged',p_image:null,p_spoiler:false}
  assert.equal(k.unwrap(await k.db.rpc('social_save_post',payload)).error,'missing')
  const response=await guest.ctx.request.post(k.base+'/community/new',{headers:{'next-action':action,origin:k.base,'content-type':'text/plain;charset=UTF-8'},data:JSON.stringify([{title:'anonymous',body:'anonymous',spoiler:false,image_url:null}])})
  assert.ok((await response.text()).includes('Entre na sua conta'))
  for(const table of ['community_posts','social_publish_log','library_activity']) assert.equal((await k.anon.from(table).select('*')).error.code,'42501')
  k.unwrap(await k.db.from('profiles').update({profile_visibility:'private'}).eq('id',a.id))
  assert.equal(k.unwrap(await k.db.rpc('social_feed',{p_actor:null,p_id:topic})).items.length,0)
  assert.equal(k.unwrap(await k.db.rpc('social_feed',{p_actor:a.id,p_id:topic})).items.length,1)
  await page.goto(k.base+'/community/new');await page.getByText(/Seu perfil está privado: esta publicação/).waitFor()
  k.unwrap(await k.db.from('profiles').update({profile_visibility:'public'}).eq('id',a.id))
 })
 await check('rate check is atomic under concurrency, counts deleted posts and enforces the rolling window',async()=>{
  const args={p_actor:b.id,p_id:null,p_title:'Concurrent',p_body:'Concurrent text',p_image:null,p_spoiler:false}
  const results=await Promise.all([k.db.rpc('social_save_post',args),k.db.rpc('social_save_post',args),k.db.rpc('social_save_post',args)])
  assert.equal(results.map(k.unwrap).filter(x=>x.id).length,1)
  k.unwrap(await k.db.from('community_posts').delete().eq('profile_id',b.id))
  assert.equal(k.unwrap(await k.db.rpc('social_save_post',args)).error,'rate')
  k.unwrap(await k.db.from('social_publish_log').update({created_at:new Date(Date.now()-120000).toISOString()}).eq('profile_id',b.id))
  for(const age of [180000,240000])k.unwrap(await k.db.from('social_publish_log').insert({profile_id:b.id,bucket:'publication',created_at:new Date(Date.now()-age).toISOString()}))
  const capped=k.unwrap(await k.db.rpc('social_save_post',args));assert.equal(capped.error,'rate');assert.ok(capped.wait>300)
 })
 await check('library sharing starts off, emits only status, and disabling purges previous events',async()=>{
  const anime=k.unwrap(await k.db.from('anime').select('id').limit(1).single())
  const library=k.unwrap(await k.db.from('user_anime').insert({profile_id:a.id,anime_id:anime.id,status:'planned',score:8,current_episode:3}).select('id').single())
  k.unwrap(await k.db.from('user_anime').update({status:'watching'}).eq('id',library.id))
  assert.equal(k.unwrap(await k.db.from('library_activity').select('*').eq('profile_id',a.id)).length,0)
  await page.goto(k.base+'/community');await page.getByRole('button',{name:'Ativar compartilhamento',exact:true}).click();await page.getByRole('button',{name:'Desativar compartilhamento',exact:true}).waitFor()
  k.unwrap(await k.db.from('user_anime').update({status:'paused'}).eq('id',library.id))
  const item=k.unwrap(await k.db.rpc('social_feed',{p_actor:null})).items.find(x=>x.type==='activity'&&x.username===a.username)
  assert.equal(item.status,'paused');assert.equal(JSON.stringify(item).includes('score'),false);assert.equal(JSON.stringify(item).includes('current_episode'),false)
  assert.equal(JSON.stringify(item).includes(a.id),false)
  k.unwrap(await k.db.from('profiles').update({profile_visibility:'private'}).eq('id',a.id));assert.equal(k.unwrap(await k.db.rpc('social_feed',{p_actor:null})).items.some(x=>x.username===a.username),false)
  k.unwrap(await k.db.from('profiles').update({profile_visibility:'public'}).eq('id',a.id))
  await page.getByRole('button',{name:'Desativar compartilhamento',exact:true}).click();await page.getByRole('button',{name:'Ativar compartilhamento',exact:true}).waitFor()
  assert.equal(k.unwrap(await k.db.from('library_activity').select('*').eq('profile_id',a.id)).length,0)
 })
 await check('following feed filters, mobile layout and confirmed deletion work',async()=>{
  k.unwrap(await k.db.rpc('social_follow',{p_actor:b.id,p_username:a.username,p_selected:true}))
  assert.ok(k.unwrap(await k.db.rpc('social_feed',{p_actor:b.id,p_mode:'following'})).items.some(x=>x.id===topic))
  k.unwrap(await k.db.rpc('social_follow',{p_actor:b.id,p_username:a.username,p_selected:false}))
  assert.equal(k.unwrap(await k.db.rpc('social_feed',{p_actor:b.id,p_mode:'following'})).items.some(x=>x.id===topic),false)
  await page.setViewportSize({width:320,height:850});await page.goto(k.base+'/community');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
  await page.goto(`${k.base}/community/${topic}/edit`);await page.getByRole('button',{name:'Excluir tópico',exact:true}).click();await page.getByRole('button',{name:'Cancelar exclusão',exact:true}).click()
  assert.ok(k.unwrap(await k.db.from('community_posts').select('id').eq('id',topic).maybeSingle()))
  await page.getByRole('button',{name:'Excluir tópico',exact:true}).click();await page.getByRole('button',{name:'Confirmar exclusão',exact:true}).click();await page.waitForURL(k.base+'/community')
  assert.equal(k.unwrap(await k.db.from('community_posts').select('id').eq('id',topic).maybeSingle()),null)
  assert.deepEqual(errors,[]);await ctx.request.get(k.base+'/community')
 })
}finally{await k.cleanup()}
console.log(`${count} topic browser checks passed; fixtures removed and original data preserved.`)
