import assert from 'node:assert/strict'
import {socialKit} from './helpers/social-live.mjs'
const extra=['profile_follows','community_posts','social_publish_log','library_activity','profile_blocks','community_comments','social_notifications','community_moderators','community_reports']
const k=await socialKit(extra);let count=0
async function check(name,fn){await fn();count++;console.log('PASS',name)}
try{
 const a=await k.user('Author'),b=await k.user('Commenter'),c=await k.user('Reply'),d=await k.user('Moderator')
 const A=await k.context(a),B=await k.context(b),C=await k.context(c),D=await k.context(d),guest=await k.context()
 const errors=[];for(const item of [A,B,C,D,guest])item.page.on('pageerror',e=>errors.push(e.message))
 const post=k.unwrap(await k.db.from('community_posts').insert({profile_id:a.id,title:'Discussão '+k.prefix,body:'Uma discussão respeitosa.',spoiler:false}).select('id').single())
 const anime=k.unwrap(await k.db.from('anime').select('id').limit(1).single())
 const review=k.unwrap(await k.db.from('community_posts').insert({profile_id:a.id,kind:'review',anime_id:anime.id,title:'Review '+k.prefix,body:'Uma review com spoilers.',spoiler:true}).select('id').single())
 const url=`${k.base}/community/${post.id}`;let root,reply,commentAction,readAction,reportAction,resolveAction
 B.page.on('request',r=>{if(r.method()==='POST'&&r.headers()['next-action'])commentAction=r.headers()['next-action']})
 await check('comment, edit, reply and spoiler disclosure work in the discussion',async()=>{
  await B.page.goto(url);await B.page.getByLabel('Seu comentário',{exact:true}).fill('<script>Comentário literal</script>')
  await B.page.getByLabel('Comentário contém spoilers',{exact:true}).check();await B.page.getByRole('button',{name:'Publicar comentário',exact:true}).click()
  await B.page.getByRole('region',{name:'Discussão',exact:true}).locator('article').getByText('@'+b.username,{exact:true}).waitFor()
  root=k.unwrap(await k.db.from('community_comments').select('id').eq('profile_id',b.id).single()).id
  const card=B.page.locator(`#comment-${root}`);assert.equal(await card.locator('details').evaluate(el=>el.open),false)
  await card.getByText('Mostrar comentário com spoilers',{exact:true}).click();await card.getByText('<script>Comentário literal</script>',{exact:true}).waitFor();assert.equal(await card.locator('script').count(),0)
  await card.getByRole('button',{name:'Editar comentário',exact:true}).click();await card.getByLabel('Editar comentário',{exact:true}).fill('Comentário editado.')
  await card.getByRole('button',{name:'Salvar comentário',exact:true}).click();await card.getByText('Comentário editado.',{exact:true}).waitFor({state:'attached'})
  await C.page.goto(url);await C.page.locator(`#comment-${root}`).getByRole('button',{name:'Responder',exact:true}).click()
  await C.page.getByLabel('Sua resposta',{exact:true}).fill('Uma resposta respeitosa.');await C.page.getByRole('button',{name:'Publicar resposta',exact:true}).click();await C.page.getByRole('region',{name:'Discussão',exact:true}).locator('article').getByText('@'+c.username,{exact:true}).waitFor()
  reply=k.unwrap(await k.db.from('community_comments').select('id,parent_id').eq('profile_id',c.id).single());assert.equal(reply.parent_id,root)
 })
 await check('moderation, comment throttle, owner and parent checks protect mutations',async()=>{
  await B.page.getByLabel('Seu comentário',{exact:true}).fill('v.i.a.d.i.n.h.o');await B.page.getByRole('button',{name:'Publicar comentário',exact:true}).click();await B.page.getByRole('alert').getByText(/linguagem discriminatória/).waitFor()
  await B.page.getByLabel('Seu comentário',{exact:true}).fill('Outro comentário respeitoso.');await B.page.getByRole('button',{name:'Publicar comentário',exact:true}).click();await B.page.getByRole('alert').getByText(/Aguarde \d+ segundos/).waitFor()
  const args={p_actor:a.id,p_post:post.id,p_id:root,p_parent:null,p_body:'forged',p_spoiler:false}
  assert.equal(k.unwrap(await k.db.rpc('social_save_comment',args)).error,'missing')
  assert.equal(k.unwrap(await k.db.rpc('social_save_comment',{...args,p_actor:d.id,p_id:null,p_post:review.id,p_parent:root})).error,'missing')
  assert.equal(k.unwrap(await k.db.rpc('social_save_comment',{...args,p_actor:d.id,p_id:null,p_parent:reply.id})).error,'missing')
  const simultaneous=await Promise.all(Array.from({length:3},()=>k.db.rpc('social_save_comment',{...args,p_actor:d.id,p_id:null})))
  assert.equal(simultaneous.map(k.unwrap).filter(x=>x.id).length,1)
  k.unwrap(await k.db.from('social_publish_log').update({created_at:new Date(Date.now()-120000).toISOString()}).eq('profile_id',d.id))
  k.unwrap(await k.db.from('social_publish_log').insert(Array.from({length:19},()=>({profile_id:d.id,bucket:'comment',created_at:new Date(Date.now()-180000).toISOString()}))))
  assert.equal(k.unwrap(await k.db.rpc('social_save_comment',{...args,p_actor:d.id,p_id:null})).error,'rate')
 })
 await check('follow, comment and reply notifications are private and can be marked read',async()=>{
  k.unwrap(await k.db.rpc('social_follow',{p_actor:c.id,p_username:a.username,p_selected:true}))
  const notifications=k.unwrap(await k.db.rpc('social_notification_list',{p_actor:a.id}));assert.ok(notifications.items.some(n=>n.kind==='follow'));assert.ok(notifications.items.some(n=>n.kind==='comment'))
  assert.ok(k.unwrap(await k.db.rpc('social_notification_list',{p_actor:b.id})).items.some(n=>n.kind==='reply'))
  A.page.on('request',r=>{if(r.method()==='POST'&&r.headers()['next-action'])readAction=r.headers()['next-action']})
  await A.page.goto(k.base+'/notifications');await A.page.getByRole('button',{name:'Marcar todas como lidas',exact:true}).click();await A.page.getByText('Lida',{exact:true}).first().waitFor()
  const own=notifications.items[0];k.unwrap(await k.db.from('social_notifications').update({read_at:null}).eq('id',own.id))
  const forged=await B.ctx.request.post(k.base+'/notifications',{headers:{'next-action':readAction,origin:k.base,'content-type':'text/plain;charset=UTF-8'},data:JSON.stringify([own.id])});assert.equal(forged.status(),200)
  assert.equal(k.unwrap(await k.db.from('social_notifications').select('read_at').eq('id',own.id).single()).read_at,null)
  k.unwrap(await k.db.from('profiles').update({profile_visibility:'private'}).eq('id',c.id));assert.equal(k.unwrap(await k.db.rpc('social_notification_list',{p_actor:a.id})).items.some(n=>n.username===c.username),false)
  await C.page.goto(url);await C.page.getByText('Seu perfil está privado: seus comentários ficarão visíveis somente para você.',{exact:true}).waitFor()
  k.unwrap(await k.db.from('profiles').update({profile_visibility:'public'}).eq('id',c.id))
 })
 await check('private reports, duplicate prevention and moderator-only queue work',async()=>{
  B.page.on('request',r=>{if(r.method()==='POST'&&r.headers()['next-action'])reportAction=r.headers()['next-action']})
  await B.page.goto(url);const postCard=B.page.locator('main > article').first();await postCard.getByRole('button',{name:'Denunciar',exact:true}).click()
  await postCard.getByLabel('Motivo da denúncia',{exact:true}).selectOption('spam');await postCard.getByLabel('Detalhes (opcional)',{exact:true}).fill('Revisar o contexto deste tópico.')
  await postCard.getByRole('button',{name:'Enviar denúncia',exact:true}).click();await postCard.getByText('Denúncia enviada para análise.',{exact:true}).waitFor()
  assert.equal(k.unwrap(await k.db.rpc('social_report',{p_actor:b.id,p_target_type:'post',p_target:post.id,p_reason:'spam',p_detail:null})).error,'duplicate')
  assert.equal(k.unwrap(await k.db.rpc('social_moderation_queue',{p_actor:b.id})),null)
  assert.equal((await B.page.goto(k.base+'/moderation')).status(),404)
  k.unwrap(await b.client.auth.updateUser({data:{moderator:true}}));assert.equal(k.unwrap(await k.db.rpc('social_moderation_queue',{p_actor:b.id})),null)
  const anon=await guest.ctx.request.post(url,{headers:{'next-action':reportAction,origin:k.base,'content-type':'text/plain;charset=UTF-8'},data:JSON.stringify(['post',post.id,'spam',''])});assert.ok((await anon.text()).includes('Entre na sua conta para denunciar.'))
  k.unwrap(await k.db.from('community_moderators').insert({profile_id:d.id}))
  const queue=k.unwrap(await k.db.rpc('social_moderation_queue',{p_actor:d.id}));assert.equal(queue.items.length,1);assert.equal(JSON.stringify(queue).includes(b.id),false)
  const publicFeed=JSON.stringify(k.unwrap(await k.db.rpc('social_feed',{p_actor:null})));assert.equal(publicFeed.includes('Revisar o contexto'),false)
  for(const table of ['profile_blocks','community_comments','social_notifications','community_moderators','community_reports'])for(const client of [k.anon,b.client])assert.equal((await client.from(table).select('*')).error.code,'42501')
 })
 await check('blocking removes both follows and hides profiles, public library, feed and comments for both accounts',async()=>{
  k.unwrap(await k.db.rpc('social_follow',{p_actor:a.id,p_username:b.username,p_selected:true}));k.unwrap(await k.db.rpc('social_follow',{p_actor:b.id,p_username:a.username,p_selected:true}))
  await B.page.goto(`${k.base}/user/${a.username}`);await B.page.getByRole('button',{name:'Bloquear pessoa',exact:true}).click();await B.page.getByRole('button',{name:'Confirmar bloqueio',exact:true}).click();await B.page.waitForURL(k.base+'/community/blocked')
  assert.equal(k.unwrap(await b.client.rpc('read_public_profile',{p_username:a.username})),null)
  assert.equal(k.unwrap(await b.client.rpc('read_public_library',{p_username:a.username})),null)
  assert.equal(k.unwrap(await a.client.rpc('read_public_profile',{p_username:b.username})),null)
  assert.equal(k.unwrap(await k.db.rpc('social_comments',{p_actor:b.id,p_post:post.id})),null)
  assert.equal(k.unwrap(await k.db.rpc('social_feed',{p_actor:b.id})).items.some(x=>x.username===a.username),false)
  assert.equal(k.unwrap(await k.db.rpc('social_people',{p_actor:b.id,p_query:k.prefix})).items.some(x=>x.username===a.username),false)
  assert.equal(k.unwrap(await k.db.rpc('social_follow',{p_actor:b.id,p_username:a.username,p_selected:true})),false)
  assert.equal(k.unwrap(await k.db.rpc('social_save_comment',{p_actor:b.id,p_post:post.id,p_id:null,p_parent:null,p_body:'blocked',p_spoiler:false})).error,'missing')
  assert.equal(k.unwrap(await k.db.from('profile_follows').select('*').eq('follower_id',b.id).eq('following_id',a.id)).length,0)
  assert.equal(k.unwrap(await k.db.from('profile_follows').select('*').eq('follower_id',a.id).eq('following_id',b.id)).length,0)
  assert.ok(k.unwrap(await k.anon.rpc('read_public_profile',{p_username:a.username})))
  await B.page.getByRole('button',{name:'Desbloquear',exact:true}).click();await B.page.getByRole('button',{name:'Confirmar desbloqueio',exact:true}).click();await B.page.getByText('Nenhuma pessoa bloqueada.',{exact:true}).waitFor()
  assert.ok(k.unwrap(await b.client.rpc('read_public_profile',{p_username:a.username})));assert.equal(k.unwrap(await k.db.from('profile_follows').select('*').eq('follower_id',b.id).eq('following_id',a.id)).length,0)
 })
 await check('review comments inherit spoiler protection; deleting a root removes replies and notifications',async()=>{
  await C.page.goto(`${k.base}/community/${review.id}`);assert.equal(await C.page.getByLabel('Comentário contém spoilers',{exact:true}).isChecked(),true)
  await B.page.goto(url);const card=B.page.locator(`#comment-${root}`);await card.getByRole('button',{name:'Excluir comentário',exact:true}).click();await card.getByRole('button',{name:'Cancelar exclusão do comentário',exact:true}).click()
  assert.ok(k.unwrap(await k.db.from('community_comments').select('id').eq('id',root).maybeSingle()))
  await card.getByRole('button',{name:'Excluir comentário',exact:true}).click();await card.getByRole('button',{name:'Confirmar exclusão do comentário',exact:true}).click();await card.waitFor({state:'detached'})
  assert.equal(k.unwrap(await k.db.from('community_comments').select('id').eq('id',reply.id).maybeSingle()),null)
  assert.equal(k.unwrap(await k.db.from('social_notifications').select('id').eq('comment_id',reply.id)).length,0)
  const response=await guest.ctx.request.post(url,{headers:{'next-action':commentAction,origin:k.base,'content-type':'text/plain;charset=UTF-8'},data:JSON.stringify([root])});assert.ok((await response.text()).includes('Entre na sua conta para comentar.'))
 })
 await check('moderation review can dismiss or remove content; forged moderator calls cannot decide reports',async()=>{
  D.page.on('request',r=>{if(r.method()==='POST'&&r.headers()['next-action'])resolveAction=r.headers()['next-action']})
  await D.page.goto(k.base+'/moderation');await D.page.getByRole('button',{name:'Encerrar sem remover',exact:true}).click();await D.page.getByText('Nenhuma denúncia pendente.',{exact:true}).waitFor()
  const reported=k.unwrap(await k.db.rpc('social_report',{p_actor:c.id,p_target_type:'post',p_target:review.id,p_reason:'spoiler',p_detail:null}))
  const denied=await B.ctx.request.post(k.base+'/moderation',{headers:{'next-action':resolveAction,origin:k.base,'content-type':'text/plain;charset=UTF-8'},data:JSON.stringify([reported.id,true])});assert.ok((await denied.text()).includes('sem permissão'))
  assert.equal(k.unwrap(await k.db.from('community_reports').select('state').eq('id',reported.id).single()).state,'pending')
  await D.page.reload();await D.page.getByRole('button',{name:'Remover conteúdo',exact:true}).click();await D.page.getByRole('button',{name:'Confirmar remoção',exact:true}).click();await D.page.getByText('Nenhuma denúncia pendente.',{exact:true}).waitFor()
  assert.equal(k.unwrap(await k.db.from('community_posts').select('id').eq('id',review.id).maybeSingle()),null)
  const notification=k.unwrap(await k.db.rpc('social_notification_list',{p_actor:a.id})).items.find(n=>n.kind==='moderation');assert.ok(notification);assert.equal(notification.username,null)
 })
 await check('mobile discussion, blocked list and notifications remain readable',async()=>{
  for(const item of [A,B,C])await item.page.setViewportSize({width:320,height:850})
  for(const [item,path]of [[A,'/notifications'],[B,'/community/blocked'],[C,`/community/${post.id}`]]){await item.page.goto(k.base+path);assert.equal(await item.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)}
  assert.deepEqual(errors,[])
 })
}finally{await k.cleanup()}
console.log(`${count} interaction browser checks passed; fixtures removed and original data preserved.`)
